apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-e1oi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-clsw-tenant/quarkus/devfile-sample-code-with-quarkus-e1oi@sha256:508b6144ebe59ccee8e9736b6a9d467682fb08916966ecaaae8ba9664a1479b6
        name: my-java-quarkus
        resources: {}
status: {}
